name: space_app_2019
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^3.1.0+1
  dio: ^3.0.3
  geolocator: ^5.1.4+2
  image_picker: ^0.6.1+8
  url_launcher: ^5.2.3
  firebase_messaging: ^5.1.6
  cloud_firestore: ^0.12.9+5
  shared_preferences: ^0.5.3+5
  mapbox_gl: ^0.0.3
  tuple: ^1.0.3
  latlong: ^0.6.1
  archive: ^2.0.10
  path_provider: ^1.3.1
  csv: ^4.0.3
  geocoder: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - lib/Images/appLogo.png

  fonts:
    - family: Icons
      fonts:
        - asset: res\icone.ttf
    - family: GoogleSans
      fonts:
        - asset: res/fonts/google_sans/GoogleSans-Regular.ttf
        - asset: res/fonts/google_sans/GoogleSans-Italic.ttf
          style: italic
        - asset: res/fonts/google_sans/GoogleSans-Medium.ttf
          weight: 600
        - asset: res/fonts/google_sans/GoogleSans-Bold.ttf
          weight: 800
